version: '3.2'

services:
    mariadb:
        image: mariadb:10.3.9
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_ROOT_PASSWORD=stripe
            - MYSQL_DATABASE=stripe
            - MYSQL_USER=stripe
            - MYSQL_PASSWORD=stripe
        volumes:
            - mariadb:/var/lib/mysql

    nginx:
        image: nginx:1.15.3-alpine
        expose:
            - 443
        depends_on:
            - php
        environment:
            DOMAIN_NAME: default:bookify.local
        volumes:
            - ./docker/nginx/certs:/etc/nginx/certs:ro
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public/:/srv/public/:ro
            - ./web/:/srv/web:ro

    php:
        build:
            context: ./docker/php
        working_dir: /srv
        depends_on:
            - mariadb
        environment:
            PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
            XDEBUG_CONFIG: remote_host=${LOCAL_IP} remote_port=${XDEBUG_PORT} idekey=${XDEBUG_IDEKEY}
        volumes:
            - ~/.composer:/home/.composer
            - ./docker/config/bashrc:/home/.bashrc
            - ./docker/config/bash_aliases:/home/.bash_aliases
            - ./docker/data/history:/home/.bash_history
            - ./:/srv/

    node:
        build:
            context: ./docker/node
        working_dir: /srv
        volumes:
            - ./:/srv/

    maildev:
        image: djfarrelly/maildev:1.0.0-rc2

volumes:
    mariadb: ~
